general {
    lock_cmd = pidof hyprlock || hyprlock          # dbus/sysd lock command (loginctl lock-session)
}

listener {
    timeout = 600                            # in seconds
    on-timeout = loginctl lock-session
}
